// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwbXn2jQ7DMlZY0IKZ9cDTf_0wi_s8EqI',
    appId: '1:402758466209:web:bcd292a39c5668c5ed4ee0',
    messagingSenderId: '402758466209',
    projectId: 'authenticationapp-88f64',
    authDomain: 'authenticationapp-88f64.firebaseapp.com',
    storageBucket: 'authenticationapp-88f64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwbXn2jQ7DMlZY0IKZ9cDTf_0wi_s8EqI',
    appId: '1:402758466209:android:bcd292a39c5668c5ed4ee0',
    messagingSenderId: '402758466209',
    projectId: 'authenticationapp-88f64',
    storageBucket: 'authenticationapp-88f64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwbXn2jQ7DMlZY0IKZ9cDTf_0wi_s8EqI',
    appId: '1:402758466209:ios:bcd292a39c5668c5ed4ee0',
    messagingSenderId: '402758466209',
    projectId: 'authenticationapp-88f64',
    storageBucket: 'authenticationapp-88f64.firebasestorage.app',
    iosBundleId: 'com.example.authenticationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwbXn2jQ7DMlZY0IKZ9cDTf_0wi_s8EqI',
    appId: '1:402758466209:ios:bcd292a39c5668c5ed4ee0',
    messagingSenderId: '402758466209',
    projectId: 'authenticationapp-88f64',
    storageBucket: 'authenticationapp-88f64.firebasestorage.app',
    iosBundleId: 'com.example.authenticationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwbXn2jQ7DMlZY0IKZ9cDTf_0wi_s8EqI',
    appId: '1:402758466209:web:bcd292a39c5668c5ed4ee0',
    messagingSenderId: '402758466209',
    projectId: 'authenticationapp-88f64',
    authDomain: 'authenticationapp-88f64.firebaseapp.com',
    storageBucket: 'authenticationapp-88f64.firebasestorage.app',
  );
}
